name: Deploy React on Amazon EC2 after Dockerizing

on:
  push:
    branches:
      - prod

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-publish-docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: 
            docker build -t adil6572/react-app:latest .
            docker push adil6572/react-app:latest
  
  apply-terraform:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    needs: build-and-publish-docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Plan Terraform
        id: terraform-plan
        working-directory: ./terraform
        run: terraform plan

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply --auto-approve
