name: Deploy React on Amazon EC2 after Dockerizing

on:
  pull_request:
    branches:
      - prod

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-docker-and-aws-infra:
    name: Build Docker Image and Apply Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t adil6572/react-app:latest
          docker push adil6572/react-app:latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform actions
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply --auto-approve tfplan
