name: Deploy React on Amazon EC2 after Dockerizing

on:
  push:
    branches:
      - prod

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-publish-docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub - Main web app container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Main web app container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/react-app:latest
          file: ./Dockerfile

  apply-terraform:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    needs: build-and-publish-docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Plan Terraform
        id: terraform-plan
        working-directory: ./terraform
        run: terraform plan

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply --auto-approve
